{% set name = "nlpannotator" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nlpannotator-{{ version }}.tar.gz
  sha256: 23b87fe3c507fb61f43193ca61e89c48423e38f248e49ae30880ec907b37204d

build:
  entry_points:
    - nlpannotator_run = nlpannotator.main:run
    - treetagger_install = nlpannotator.install_treetagger:install_tagger
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }},<4
    - spacy <3.5.0,>=3.4.0
    - stanza <=1.4.0
    - python-flair <=0.11.3
    - somajo
    - treetaggerwrapper
    - jsonschema
    - importlib-resources >=5.8

test:
  imports:
    - nlpannotator
  commands:
    - treetagger_install --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Annotator combining different NLP pipelines
  home: https://github.com/ssciwr/argumentation-management
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iulusoy
